modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory
license="MIT"
#issueTrackerURL="https://your.issue.tracker.example/"

[[mods]]
modId="attributizedskills"
version="1.2.0"
displayName="Attributized Skills"
logoFile="attributizedskills.png"
credits="dragoni7, majikdev"
authors="undertaker_j, Bastrii"
description='''
 Attributized Skills is a spiritual successor of RPGskillable by dragoni_7.
 What initially started as a fork led to a complete overhaul of the entire codebase,
 leaving essentially less than 10% of the initial assets and code.
 To cover all bases though, this project was made with permission from dragoni_7.
'''

[[dependencies.attributizedskills]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.attributizedskills]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
