modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory
license="All Rights Reserved"
#issueTrackerURL="https://your.issue.tracker.example/"

[[mods]]
modId="attributizedskills"
version="1.1.0"
displayName="Attributized Skills"
logoFile="attributizedskills.png" # если логотип изменён, положите его в корень jar
credits="dragoni7, majikdev"
authors="undertaker_j, Bastrii"
description='''
 Attributized Skills is a spiritual successor of RPGskillable by dragoni_7.
 What initially started as a fork led to a complete overhaul of the entire codebase,
 leaving essentially less than 10% of the initial assets and code.
 To cover all bases though, this project was made with permission from dragoni_7.
'''

[[dependencies.attributizedskills]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.attributizedskills]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
